name: 'lab04-actions'
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:      
      - name: Git clone
        uses: actions/checkout@v3
        with:
          ref: lab04_master
        
      - name: Git checkout
        run : git checkout lab04_master
        
      - name: Git pull
        run : git pull origin lab04_master
    
      - name: Test_formatter_lib
        working-directory: formatter_lib
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
          
      - name: Test_formatter_ex_lib
        working-directory: formatter_ex_lib
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
          
      - name: Test_hello_world_application
        working-directory: hello_world_application
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
